apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: masakhane-model-cache-volume-claim
  namespace: masakhane
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
