"""empty message

Revision ID: 2298f5583677
Revises: b95776d05ad8
Create Date: 2021-02-09 00:07:09.582090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2298f5583677'
down_revision = 'b95776d05ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('masakhane_input_key', 'masakhane', type_='unique')
    op.drop_constraint('masakhane_review_key', 'masakhane', type_='unique')
    op.drop_constraint('masakhane_stars_key', 'masakhane', type_='unique')
    op.create_unique_constraint(None, 'masakhane', ['input', 'review', 'stars'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'masakhane', type_='unique')
    op.create_unique_constraint('masakhane_stars_key', 'masakhane', ['stars'])
    op.create_unique_constraint('masakhane_review_key', 'masakhane', ['review'])
    op.create_unique_constraint('masakhane_input_key', 'masakhane', ['input'])
    # ### end Alembic commands ###
