"""empty message

Revision ID: 4967ebaa9dbf
Revises: 2298f5583677
Create Date: 2021-02-12 17:44:51.068053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4967ebaa9dbf'
down_revision = '2298f5583677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('masakhane_input_review_stars_key', 'masakhane', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('masakhane_input_review_stars_key', 'masakhane', ['input', 'review', 'stars'])
    # ### end Alembic commands ###
