"""empty message

Revision ID: 887abb2468ee
Revises: 
Create Date: 2021-02-08 23:43:02.919095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887abb2468ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masakhane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_lang', sa.String(length=20), nullable=False),
    sa.Column('tgt_lang', sa.String(length=20), nullable=False),
    sa.Column('input', sa.String(length=800), nullable=False),
    sa.Column('review', sa.String(length=800), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('input'),
    sa.UniqueConstraint('review'),
    sa.UniqueConstraint('src_lang'),
    sa.UniqueConstraint('tgt_lang')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('masakhane')
    # ### end Alembic commands ###
