"""empty message

Revision ID: 9691767e83b7
Revises: 887abb2468ee
Create Date: 2021-02-08 23:53:03.760644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9691767e83b7'
down_revision = '887abb2468ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masakhane', sa.Column('token', sa.String(length=20), nullable=False))
    op.drop_constraint('masakhane_input_key', 'masakhane', type_='unique')
    op.drop_constraint('masakhane_review_key', 'masakhane', type_='unique')
    op.drop_constraint('masakhane_tgt_lang_key', 'masakhane', type_='unique')
    op.create_unique_constraint(None, 'masakhane', ['token'])
    op.drop_column('masakhane', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masakhane', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'masakhane', type_='unique')
    op.create_unique_constraint('masakhane_tgt_lang_key', 'masakhane', ['tgt_lang'])
    op.create_unique_constraint('masakhane_review_key', 'masakhane', ['review'])
    op.create_unique_constraint('masakhane_input_key', 'masakhane', ['input'])
    op.drop_column('masakhane', 'token')
    # ### end Alembic commands ###
