apiVersion: v1
kind: PersistentVolume
metadata:
  name: translation-volume-storage
  namespace: masakhane
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /models_datastore # the host on the minikube vm
