apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: translation-pod
  namespace: masakhane
spec:
  name: translation-worker
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: masakhane/translation:alpha 
          name: translation-container
          imagePullPolicy: IfNotPresent
          env:
          - name: TRANSFORMERS_CACHE
            value: "/models_datastore/.cache"
          - name: GUNICORN_WORKERS
            value: '2'
          - name: GRPC_WORKERS
            value: '2'
          - name: SELDON_LOG_LEVEL
            value: DEBUG
          - name: SELDON_DEBUG
            value: 'True'
          - name: FLASK_DEBUG
            value: 'True'
          volumeMounts:
            - mountPath: "/models_datastore/" # mount the cache volume here
              name: translation-volume-storage
          resources:
            requests:
              memory: 2048Mi
              cpu: 2048m
            limits:
              memory: 3048Mi
              cpu: 3048m
        terminationGracePeriodSeconds: 1
        volumes:
        - name: translation-volume-storage
          persistentVolumeClaim:
            claimName: masakhane-model-cache-volume-claim
    graph:
      envSecretRefName: masakhane-container-secret
      children: []
      endpoint:
        type: REST
      name: translation-container
      type: MODEL
      parameters: 
      - name: model_path
        type: STRING
        value: "/models_datastore/" # this should come form volume.
      - name: src_lang
        type: STRING
        value: "en"
      - name: tgt_lang
        type: STRING
        value: "sw"
    labels:
      version: v1
    name: translation-predictor
    replicas: 1



